# Assignment 6 — NumPy-II

**Name:** Deepak

## Q1. Sensor Readings

In [1]:
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

corrected_temperature = temperature + 2
print("a.", corrected_temperature)

fahrenheit = (9/5) * temperature + 32
print("b.", fahrenheit)

readings_greater_32 = temperature[temperature > 32]
print("c.", readings_greater_32)

count_greater_32 = np.sum(temperature > 32)
print("d.", count_greater_32)

print("e. Vectorization performs operations on the whole NumPy array without an explicit loop.")
print("   Boolean indexing selects values satisfying a condition. Both are concise and efficient.")

a. [27 30 33 37 40 29 35 42]
b. [ 77.   82.4  87.8  95.  100.4  80.6  91.4 104. ]
c. [35 38 33 40]
d. 4
e. Vectorization performs operations on the whole NumPy array without an explicit loop.
   Boolean indexing selects values satisfying a condition. Both are concise and efficient.


## Q2. Daily Steps

In [2]:
steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

print("a. Total steps:", np.sum(steps))

print("b. Mean steps:", np.mean(steps))

print("c. Maximum:", np.max(steps))
print("   Minimum:", np.min(steps))

print("d. Total for each day:", np.sum(steps, axis=0))

print("e. Total for each user:", np.sum(steps, axis=1))

print("f. Position of maximum (user, day):",
      np.unravel_index(np.argmax(steps), steps.shape))

a. Total steps: 84200
b. Mean steps: 7016.666666666667
c. Maximum: 9500
   Minimum: 4500
d. Total for each day: [26500 27300 30400]
e. Total for each user: [18300 24500 14400 27000]
f. Position of maximum (user, day): (np.int64(3), np.int64(2))


## Q3. NumPy Arrays, Slicing, Copying and Reshaping

In [3]:
original = np.array([1, 2, 3, 4, 5, 6])
print("a. Original:", original)

subset = original[1:4]
print("b. Subset:", subset)

subset[0] = 999
print("c. Original:", original)
print("   Subset:", subset)

copied = original[1:4].copy()
copied[0] = 500
print("d. Original:", original)
print("   Copied:", copied)

matrix = np.arange(1, 13).reshape(3, 4)
print("e. Matrix:")
print(matrix)

print("f. First row:", matrix[0])
print("   Last row:", matrix[-1])
print("   Second column:", matrix[:, 1])
print("   Rows 1-2 and columns 2-3:")
print(matrix[0:2, 1:3])

flattened = matrix.flatten()
raveled = matrix.ravel()
print("g. flatten():", flattened)
print("   ravel():", raveled)

raveled[0] = 1000
print("h. Matrix after modifying ravel():")
print(matrix)

flattened[1] = 2000
print("i. Matrix after modifying flatten():")
print(matrix)

print("j. Shape:", matrix.shape)
print("   ndim:", matrix.ndim)
print("   size:", matrix.size)
print("   dtype:", matrix.dtype)

a. Original: [1 2 3 4 5 6]
b. Subset: [2 3 4]
c. Original: [  1 999   3   4   5   6]
   Subset: [999   3   4]
d. Original: [  1 999   3   4   5   6]
   Copied: [500   3   4]
e. Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
f. First row: [1 2 3 4]
   Last row: [ 9 10 11 12]
   Second column: [ 2  6 10]
   Rows 1-2 and columns 2-3:
[[2 3]
 [6 7]]
g. flatten(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
   ravel(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
h. Matrix after modifying ravel():
[[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]
i. Matrix after modifying flatten():
[[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]
j. Shape: (3, 4)
   ndim: 2
   size: 12
   dtype: int64


## Q4. Cognitive-Assistive System and OLS

In [4]:
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])

print("a. Shape:", X.shape)
print("   Dimensions:", X.ndim)

X_T = X.T
print("\nb. X.T:")
print(X_T)
print("   Transpose changes rows into columns and columns into rows.")

XTX = X.T @ X
print("\nc. X.T @ X:")
print(XTX)

XTX_inv = np.linalg.inv(XTX)
print("\nd. Inverse of X.T @ X:")
print(XTX_inv)

beta = XTX_inv @ X.T @ y
print("\ne. Coefficients beta:")
print(beta)

print("\nf. beta[0] = Sleep Hours coefficient")
print("   beta[1] = Activity Level coefficient")
print("   beta[2] = Stress Level coefficient")
print("   Each coefficient estimates the change in assistance score for")
print("   a one-unit increase in that feature, keeping the others fixed.")

new_user = np.array([5, 40, 7])
predicted_score = new_user @ beta
print("\ng. New user:", new_user)
print("   Predicted assistance score:", predicted_score)

a. Shape: (4, 3)
   Dimensions: 2

b. X.T:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
   Transpose changes rows into columns and columns into rows.

c. X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]

d. Inverse of X.T @ X:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]

e. Coefficients beta:
[-0.15921454  0.14083853 10.06302242]

f. beta[0] = Sleep Hours coefficient
   beta[1] = Activity Level coefficient
   beta[2] = Stress Level coefficient
   Each coefficient estimates the change in assistance score for
   a one-unit increase in that feature, keeping the others fixed.

g. New user: [ 5 40  7]
   Predicted assistance score: 75.27862544778861
